global:
  scrape_interval: 3s
  evaluation_interval: 3s

scrape_configs:
  - job_name: 'TemplateServiceSpringBoot-WebMetrics'
    metrics_path: '/api/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'craft'

  - job_name: 'TemplateServiceSpringBoot-WorkerMetrics'
    metrics_path: '/api/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'host.docker.internal:8081' ]
        labels:
          application: 'craft'